**Exercice 2**

In [1]:
import pandas as pd
import numpy as np

In [57]:
name = open('imports-85.names', 'r')
for x in name:
  print(x)
#print(name.read())

1. Title: 1985 Auto Imports Database



2. Source Information:

   -- Creator/Donor: Jeffrey C. Schlimmer (Jeffrey.Schlimmer@a.gp.cs.cmu.edu)

   -- Date: 19 May 1987

   -- Sources:

     1) 1985 Model Import Car and Truck Specifications, 1985 Ward's

        Automotive Yearbook.

     2) Personal Auto Manuals, Insurance Services Office, 160 Water

        Street, New York, NY 10038

     3) Insurance Collision Report, Insurance Institute for Highway

        Safety, Watergate 600, Washington, DC 20037



3. Past Usage:

   -- Kibler,~D., Aha,~D.~W., \& Albert,~M. (1989).  Instance-based prediction

      of real-valued attributes.  {\it Computational Intelligence}, {\it 5},

      51--57.

	 -- Predicted price of car using all numeric and Boolean attributes

	 -- Method: an instance-based learning (IBL) algorithm derived from a

	    localized k-nearest neighbor algorithm.  Compared with a

	    linear regression prediction...so all instances

	    with missing attribute values were discarded.  This resulted with

	    a training set of 159 instances, which was also used as a test

	    set (minus the actual instance during testing).

	 -- Results: Percent Average Deviation Error of Prediction from Actual

	    -- 11.84% for the IBL algorithm

	    -- 14.12% for the resulting linear regression equation



4. Relevant Information:

   -- Description

      This data set consists of three types of entities: (a) the

      specification of an auto in terms of various characteristics, (b)

      its assigned insurance risk rating, (c) its normalized losses in use

      as compared to other cars.  The second rating corresponds to the

      degree to which the auto is more risky than its price indicates.

      Cars are initially assigned a risk factor symbol associated with its

      price.   Then, if it is more risky (or less), this symbol is

      adjusted by moving it up (or down) the scale.  Actuarians call this

      process "symboling".  A value of +3 indicates that the auto is

      risky, -3 that it is probably pretty safe.



      The third factor is the relative average loss payment per insured

      vehicle year.  This value is normalized for all autos within a

      particular size classification (two-door small, station wagons,

      sports/speciality, etc...), and represents the average loss per car

      per year.



   -- Note: Several of the attributes in the database could be used as a

            "class" attribute.



5. Number of Instances: 205



6. Number of Attributes: 26 total

   -- 15 continuous

   -- 1 integer

   -- 10 nominal



7. Attribute Information:

     Attribute:                Attribute Range:

     ------------------        -----------------------------------------------

  1. symboling:                -3, -2, -1, 0, 1, 2, 3.

  2. normalized-losses:        continuous from 65 to 256.

  3. make:                     alfa-romero, audi, bmw, chevrolet, dodge, honda,

                               isuzu, jaguar, mazda, mercedes-benz, mercury,

                               mitsubishi, nissan, peugot, plymouth, porsche,

                               renault, saab, subaru, toyota, volkswagen, volvo

  4. fuel-type:                diesel, gas.

  5. aspiration:               std, turbo.

  6. num-of-doors:             four, two.

  7. body-style:               hardtop, wagon, sedan, hatchback, convertible.

  8. drive-wheels:             4wd, fwd, rwd.

  9. engine-location:          front, rear.

 10. wheel-base:               continuous from 86.6 120.9.

 11. length:                   continuous from 141.1 to 208.1.

 12. width:                    continuous from 60.3 to 72.3.

 13. height:                   continuous from 47.8 to 59.8.

 14. curb-weight:              continuous from 1488 to 4066.

 15. engine-type:              dohc, dohcv, l, ohc, ohcf, ohcv, rotor.

 16. num-of-cylinders:         eight, five, four, six, three, twelve, two.

 17. engine-size:              continuous from 61 to 326.

 18. fuel-system:              1bbl, 2bbl, 4bbl, idi, mfi, mpfi, spdi, spfi.

 19. bore:                     continuous from 2.54 to 3.94.

 20. stroke:                   continuous from 2.07 to 4.17.

 21. compression-ratio:        continuous from 7 to 23.

 22. horsepower:               continuous from 48 to 288.

 23. peak-rpm:                 continuous from 4150 to 6600.

 24. city-mpg:                 continuous from 13 to 49.

 25. highway-mpg:              continuous from 16 to 54.

 26. price:                    continuous from 5118 to 45400.



8. Missing Attribute Values: (denoted by "?")

   Attribute #:   Number of instances missing a value:

   2.             41

   6.             2

   19.            4

   20.            4

   22.            2

   23.            2

   26.            4

In [63]:
nom = ['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 
       'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 
       'peak-rpm', 'city-mpg', 'highway-mpg', 'price']
df = pd.read_csv('imports-85.data',na_values='?', names = nom)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

Q1

In [64]:
df.isnull().any(axis=0)

symboling            False
normalized-losses     True
make                 False
fuel-type            False
aspiration           False
num-of-doors          True
body-style           False
drive-wheels         False
engine-location      False
wheel-base           False
length               False
width                False
height               False
curb-weight          False
engine-type          False
num-of-cylinders     False
engine-size          False
fuel-system          False
bore                  True
stroke                True
compression-ratio    False
horsepower            True
peak-rpm              True
city-mpg             False
highway-mpg          False
price                 True
dtype: bool

Q2

In [65]:
df.isnull().sum(axis=0)

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

Q3

In [66]:
cvrt = {'two':2, 'four':4, np.nan:np.nan}

df['num-of-doors'] = df['num-of-doors'].map(lambda x: cvrt[x])
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,2.0,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,4.0,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,4.0,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,4.0,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [67]:
nacol = df[['normalized-losses', 'num-of-doors', 'bore', 'stroke', 'horsepower', 'peak-rpm', 'price']]
nacol

,normalized-losses,num-of-doors,bore,stroke,horsepower,peak-rpm,price
0,NaN,2.0,3.47,2.68,111.0,5000.0,13495.0
1,NaN,2.0,3.47,2.68,111.0,5000.0,16500.0
2,NaN,2.0,2.68,3.47,154.0,5000.0,16500.0
3,164.0,4.0,3.19,3.40,102.0,5500.0,13950.0
4,164.0,4.0,3.19,3.40,115.0,5500.0,17450.0
...,...,...,...,...,...,...,...
200,95.0,4.0,3.78,3.15,114.0,5400.0,16845.0
201,95.0,4.0,3.78,3.15,160.0,5300.0,19045.0
202,95.0,4.0,3.58,2.87,134.0,5500.0,21485.0
203,95.0,4.0,3.01,3.40,106.0,4800.0,22470.0
204,95.0,4.0,3.78,3.15,114.0,5400.0,22625.0

In [68]:
nacol.corr()

,normalized-losses,num-of-doors,bore,stroke,horsepower,peak-rpm,price
normalized-losses,1.000000,-0.407134,-0.036167,0.065627,0.295772,0.264597,0.203254
num-of-doors,-0.407134,1.000000,0.114501,-0.010697,-0.124963,-0.242485,0.046532
bore,-0.036167,0.114501,1.000000,-0.055909,0.577273,-0.264269,0.543436
stroke,0.065627,-0.010697,-0.055909,1.000000,0.090254,-0.071493,0.082310
horsepower,0.295772,-0.124963,0.577273,0.090254,1.000000,0.130971,0.810533
peak-rpm,0.264597,-0.242485,-0.264269,-0.071493,0.130971,1.000000,-0.101649
price,0.203254,0.046532,0.543436,0.082310,0.810533,-0.101649,1.000000

In [35]:
from sklearn import preprocessing

In [69]:
# drop les lignes que la valeur 'price' car il est tres influent
df = df.dropna(subset=['price'])

#median (assez influent)
#      df['price'].fillna(value=np.round(df['price'].median(), decimals=2), inplace=True)
df['normalized-losses'].fillna(value=np.round(df['normalized-losses'].mean(), decimals=2), inplace=True)
df['bore'].fillna(value=np.round(df['bore'].mean(), decimals=2), inplace=True)
df['horsepower'].fillna(value=np.round(df['horsepower'].median(), decimals=2), inplace=True)

#mean
df['num-of-doors'].fillna(value=np.round(df['num-of-doors'].mean(), decimals=2), inplace=True)
df['stroke'].fillna(value=np.round(df['stroke'].mean(), decimals=2), inplace=True)
df['peak-rpm'].fillna(value=np.round(df['peak-rpm'].mean(), decimals=2), inplace=True)

df

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)
/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,alfa-romero,gas,std,2.0,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,4.0,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,4.0,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,4.0,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [70]:
df.isnull().any(axis=0)

symboling            False
normalized-losses    False
make                 False
fuel-type            False
aspiration           False
num-of-doors         False
body-style           False
drive-wheels         False
engine-location      False
wheel-base           False
length               False
width                False
height               False
curb-weight          False
engine-type          False
num-of-cylinders     False
engine-size          False
fuel-system          False
bore                 False
stroke               False
compression-ratio    False
horsepower           False
peak-rpm             False
city-mpg             False
highway-mpg          False
price                False
dtype: bool

**Exercice 3**

Q1

In [71]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
aspiration            object
num-of-doors         float64
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

**il y a 9 caracteristique/attribut qualitative type object et 17 quantitative dont 12 continue (float64) et 5 discret (int64)**

Q2

In [72]:
pd.set_option('display.max_columns', None)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,alfa-romero,gas,std,2.0,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,4.0,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,4.0,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,188.8,68.9,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,188.8,68.8,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,4.0,sedan,rwd,front,109.1,188.8,68.9,55.5,3217,ohc,six,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [75]:
df['body-style'].unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [76]:
df['drive-wheels'].unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [77]:
df['engine-location'].unique()

array(['front', 'rear'], dtype=object)

In [74]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [78]:
df['body-style'] = pd.Categorical(df['body-style'], categories=['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'])
df['drive-wheels'] = pd.Categorical(df['drive-wheels'], categories=['rwd', 'fwd', '4wd'])
df['engine-location'] = pd.Categorical(df['engine-location'], categories=['front', 'rear'])


nbr = {'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'eight':8, 'twelve':12}

df['num-of-cylinders'] = df['num-of-cylinders'].map(lambda x: nbr[x])


df.dtypes

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

symboling               int64
normalized-losses     float64
make                   object
fuel-type              object
aspiration             object
num-of-doors          float64
body-style           category
drive-wheels         category
engine-location      category
wheel-base            float64
length                float64
width                 float64
height                float64
curb-weight             int64
engine-type            object
num-of-cylinders        int64
engine-size             int64
fuel-system            object
bore                  float64
stroke                float64
compression-ratio     float64
horsepower            float64
peak-rpm              float64
city-mpg                int64
highway-mpg             int64
price                 float64
dtype: object

Q3

In [79]:
lw = df[['length', 'width']]
lw

     length  width
0     168.8   64.1
1     168.8   64.1
2     171.2   65.5
3     176.6   66.2
4     176.6   66.4
..      ...    ...
200   188.8   68.9
201   188.8   68.8
202   188.8   68.9
203   188.8   68.9
204   188.8   68.9

[201 rows x 2 columns]

In [80]:
minmax = preprocessing.MinMaxScaler(feature_range= (0,1))
lws = minmax.fit_transform(lw)
lws

array([[0.41343284, 0.32478632],
       [0.41343284, 0.32478632],
       [0.44925373, 0.44444444],
       [0.52985075, 0.5042735 ],
       [0.52985075, 0.52136752],
       [0.54029851, 0.51282051],
       [0.77014925, 0.94871795],
       [0.77014925, 0.94871795],
       [0.77014925, 0.94871795],
       [0.53283582, 0.38461538],
       [0.53283582, 0.38461538],
       [0.53283582, 0.38461538],
       [0.53283582, 0.38461538],
       [0.71492537, 0.56410256],
       [0.71492537, 0.56410256],
       [0.78656716, 0.64957265],
       [0.83432836, 0.90598291],
       [0.        , 0.        ],
       [0.22089552, 0.28205128],
       [0.2641791 , 0.28205128],
       [0.24179104, 0.2991453 ],
       [0.24179104, 0.2991453 ],
       [0.24179104, 0.2991453 ],
       [0.24179104, 0.2991453 ],
       [0.24179104, 0.2991453 ],
       [0.24179104, 0.2991453 ],
       [0.24179104, 0.2991453 ],
       [0.5       , 0.36752137],
       [0.47910448, 0.51282051],
       [0.05223881, 0.30769231],
       [0.05223881, 0.30769231],
       [0.13283582, 0.31623932],
       [0.13283582, 0.31623932],
       [0.13283582, 0.31623932],
       [0.33283582, 0.31623932],
       [0.23880597, 0.30769231],
       [0.39402985, 0.41880342],
       [0.39402985, 0.41880342],
       [0.5119403 , 0.41880342],
       [0.5119403 , 0.18803419],
       [0.5119403 , 0.41880342],
       [0.41791045, 0.48717949],
       [0.44179104, 0.12820513],
       [0.47014925, 0.41880342],
       [0.87313433, 0.79487179],
       [0.87313433, 0.79487179],
       [0.75522388, 0.88034188],
       [0.26865672, 0.33333333],
       [0.26865672, 0.33333333],
       [0.26865672, 0.33333333],
       [0.38358209, 0.33333333],
       [0.38358209, 0.33333333],
       [0.41641791, 0.46153846],
       [0.41641791, 0.46153846],
       [0.41641791, 0.46153846],
       [0.41641791, 0.46153846],
       [0.54776119, 0.52991453],
       [0.54776119, 0.52991453],
       [0.54776119, 0.52991453],
       [0.54776119, 0.52991453],
       [0.54776119, 0.52991453],
       [0.54776119, 0.52991453],
       [0.50597015, 0.4957265 ],
       [0.50597015, 0.4957265 ],
       [0.74328358, 0.85470085],
       [0.74328358, 0.85470085],
       [0.69253731, 0.85470085],
       [0.91791045, 0.97435897],
       [0.91791045, 0.97435897],
       [0.58507463, 0.87179487],
       [1.        , 0.97435897],
       [0.86716418, 1.        ],
       [0.55671642, 0.65811966],
       [0.24179104, 0.35042735],
       [0.24179104, 0.35042735],
       [0.24179104, 0.35042735],
       [0.24179104, 0.2991453 ],
       [0.4761194 , 0.43589744],
       [0.4761194 , 0.43589744],
       [0.47910448, 0.51282051],
       [0.47910448, 0.51282051],
       [0.47910448, 0.51282051],
       [0.46716418, 0.43589744],
       [0.46716418, 0.43589744],
       [0.46716418, 0.43589744],
       [0.46716418, 0.43589744],
       [0.36119403, 0.2991453 ],
       [0.36119403, 0.2991453 ],
       [0.36119403, 0.2991453 ],
       [0.36119403, 0.2991453 ],
       [0.43432836, 0.2991453 ],
       [0.36119403, 0.2991453 ],
       [0.36567164, 0.2991453 ],
       [0.36119403, 0.2991453 ],
       [0.43432836, 0.2991453 ],
       [0.31791045, 0.2991453 ],
       [0.48208955, 0.41880342],
       [0.48208955, 0.41880342],
       [0.60597015, 0.52991453],
       [0.64925373, 0.52991453],
       [0.64925373, 0.52991453],
       [0.44179104, 0.64957265],
       [0.44179104, 0.64957265],
       [0.55820896, 0.64957265],
       [0.68059701, 0.69230769],
       [0.68059701, 0.69230769],
       [0.86268657, 0.69230769],
       [0.86268657, 0.69230769],
       [0.68059701, 0.69230769],
       [0.68059701, 0.69230769],
       [0.86268657, 0.69230769],
       [0.86268657, 0.69230769],
       [0.68059701, 0.69230769],
       [0.68059701, 0.69230769],
       [0.68059701, 0.68376068],
       [0.24179104, 0.2991453 ],
       [0.24179104, 0.2991453 ],
       [0.24179104, 0.2991453 ],
       [0.39104478, 0.2991453 ],
       [0.39104478, 0.2991453 ],
       [0.5       , 0.36752137],
       [0.47910448, 0.51282051],
       [0.41492537, 0.68376068],
       [0.41492537, 0.4017094 ],
       [0.41492537, 0.4017094 ],
       [0.41492537, 0.4017094 ],
       [0.60298507, 0.52991453],
       [0.53283582, 0.53846154],
       [0.67910448, 0.52991453],
       [0.67910448, 0.52991453],
       [0.67910448, 0.52991453],
       [0.67910448, 0.52991453],
       [0.67910448, 0.52991453],
       [0.67910448, 0.52991453],
       [0.2358209 , 0.26495726],
       [0.25074627, 0.28205128],
       [0.24179104, 0.2991453 ],
       [0.46119403, 0.43589744],
       [0.46119403, 0.43589744],
       [0.46119403, 0.43589744],
       [0.46119403, 0.43589744],
       [0.46119403, 0.43589744],
       [0.48358209, 0.43589744],
       [0.48358209, 0.43589744],
       [0.48507463, 0.43589744],
       [0.48507463, 0.43589744],
       [0.26268657, 0.28205128],
       [0.26268657, 0.28205128],
       [0.26268657, 0.28205128],
       [0.42686567, 0.28205128],
       [0.42686567, 0.28205128],
       [0.42686567, 0.28205128],
       [0.3761194 , 0.35042735],
       [0.3761194 , 0.35042735],
       [0.3761194 , 0.35042735],
       [0.3761194 , 0.35042735],
       [0.3761194 , 0.35042735],
       [0.3761194 , 0.35042735],
       [0.3761194 , 0.35042735],
       [0.4119403 , 0.31623932],
       [0.4119403 , 0.31623932],
       [0.4119403 , 0.31623932],
       [0.4119403 , 0.31623932],
       [0.5238806 , 0.45299145],
       [0.5238806 , 0.45299145],
       [0.5238806 , 0.45299145],
       [0.5238806 , 0.45299145],
       [0.5238806 , 0.45299145],
       [0.5238806 , 0.45299145],
       [0.51492537, 0.52991453],
       [0.51492537, 0.52991453],
       [0.51492537, 0.52991453],
       [0.51492537, 0.52991453],
       [0.51492537, 0.52991453],
       [0.63283582, 0.63247863],
       [0.63283582, 0.63247863],
       [0.69701493, 0.52991453],
       [0.69701493, 0.52991453],
       [0.45671642, 0.44444444],
       [0.45671642, 0.44444444],
       [0.45671642, 0.44444444],
       [0.45671642, 0.44444444],
       [0.45671642, 0.44444444],
       [0.45671642, 0.44444444],
       [0.45671642, 0.44444444],
       [0.27164179, 0.33333333],
       [0.36716418, 0.31623932],
       [0.58358209, 0.56410256],
       [0.58358209, 0.56410256],
       [0.62686567, 0.56410256],
       [0.7119403 , 0.58974359],
       [0.7119403 , 0.58974359],
       [0.7119403 , 0.58974359],
       [0.7119403 , 0.58974359],
       [0.7119403 , 0.58974359],
       [0.7119403 , 0.58974359],
       [0.7119403 , 0.73504274],
       [0.7119403 , 0.72649573],
       [0.7119403 , 0.73504274],
       [0.7119403 , 0.73504274],
       [0.7119403 , 0.73504274]])

In [81]:
df[['length', 'width']] = lws
df

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3678: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,0.413433,0.324786,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,0.413433,0.324786,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,alfa-romero,gas,std,2.0,hatchback,rwd,front,94.5,0.449254,0.444444,52.4,2823,ohcv,6,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,4.0,sedan,fwd,front,99.8,0.529851,0.504274,54.3,2337,ohc,4,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,4.0,sedan,4wd,front,99.4,0.529851,0.521368,54.3,2824,ohc,5,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,0.711940,0.735043,55.5,2952,ohc,4,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,0.711940,0.726496,55.5,3049,ohc,4,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,0.711940,0.735043,55.5,3012,ohcv,6,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,4.0,sedan,rwd,front,109.1,0.711940,0.735043,55.5,3217,ohc,6,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,0.711940,0.735043,55.5,3062,ohc,4,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

Q4

In [84]:
df['fuel-type'].unique()

array(['gas', 'diesel'], dtype=object)

In [86]:
df['fuel-type'] = pd.Categorical(df['fuel-type'], categories=['gas', 'diesel'])
df.dtypes

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

symboling               int64
normalized-losses     float64
make                   object
fuel-type            category
aspiration             object
num-of-doors          float64
body-style           category
drive-wheels         category
engine-location      category
wheel-base            float64
length                float64
width                 float64
height                float64
curb-weight             int64
engine-type            object
num-of-cylinders        int64
engine-size             int64
fuel-system            object
bore                  float64
stroke                float64
compression-ratio     float64
horsepower            float64
peak-rpm              float64
city-mpg                int64
highway-mpg             int64
price                 float64
dtype: object